### ISSUE TITLE
SetupAuthInteractor should use a CommonUserFactory

### ISSUE THREAD

**Issue by alextmacri** [hadi-naqvi/Aegis-Pass#20]
Line 35 of SetupAuthInteractor.java manually instantiates a CommonUser instead of using a CommonUserFactory. This line should be using a CommonUserFactory, which also means we need to add a CommonUserFactory attribute to that class, and pass it in through the constructor, which then assigns it. This means we will also have to pass in a factory wherever a SetupAuthInteractor is used.

**Comment by hadi-naqvi** [comment]
Issue has been fixed as of the most recent PR SetupAuth:
- https://github.com/hadi-naqvi/Aegis-Pass/pull/10
